const users = [
  {
    id: 1,
    name: "Ali Khan",
    profession: "Frontend Developer",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    likes: "12.4k",
    comments: "3.2k",
    shares: "1.1k",
  },
  {
    id: 2,
    name: "Sara Ahmed",
    profession: "UI/UX Designer",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    likes: "24.8k",
    comments: "5.7k",
    shares: "2.3k",
  },
  {
    id: 3,
    name: "Usman Tariq",
    profession: "YouTuber",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    likes: "60.4k",
    comments: "20k",
    shares: "12.4k",
  },
  {
    id: 4,
    name: "Ayesha Noor",
    profession: "Content Creator",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    likes: "34.1k",
    comments: "8.2k",
    shares: "4.5k",
  },
  {
    id: 5,
    name: "Bilal Sheikh",
    profession: "Backend Developer",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    likes: "17.9k",
    comments: "4.1k",
    shares: "2.0k",
  },
  {
    id: 6,
    name: "Hina Malik",
    profession: "Blogger",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    likes: "28.5k",
    comments: "6.8k",
    shares: "3.7k",
  },
  {
    id: 7,
    name: "Ahmed Raza",
    profession: "Full Stack Developer",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    likes: "40.2k",
    comments: "9.4k",
    shares: "5.6k",
  },
  {
    id: 8,
    name: "Fatima Zahra",
    profession: "Graphic Designer",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    likes: "19.7k",
    comments: "4.9k",
    shares: "2.8k",
  },
  {
    id: 9,
    name: "Hamza Ali",
    profession: "React Developer",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    likes: "22.3k",
    comments: "5.1k",
    shares: "3.0k",
  },
  {
    id: 10,
    name: "Mariam Khan",
    profession: "Digital Marketer",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    likes: "31.6k",
    comments: "7.5k",
    shares: "4.2k",
  },
  {
    id: 11,
    name: "Zain Ahmed",
    profession: "Software Engineer",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    likes: "26.4k",
    comments: "6.1k",
    shares: "3.4k",
  },
  {
    id: 12,
    name: "Iqra Shah",
    profession: "Freelancer",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    likes: "15.8k",
    comments: "3.7k",
    shares: "1.9k",
  },
  {
    id: 13,
    name: "Saad Hassan",
    profession: "Web Developer",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    likes: "18.2k",
    comments: "4.2k",
    shares: "2.2k",
  },
  {
    id: 14,
    name: "Noor Fatima",
    profession: "Influencer",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    likes: "70.1k",
    comments: "25.4k",
    shares: "15.2k",
  },
  {
    id: 15,
    name: "Danish Malik",
    profession: "Mobile App Developer",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    likes: "21.3k",
    comments: "5.5k",
    shares: "2.9k",
  },
  {
    id: 16,
    name: "Rabia Javed",
    profession: "Teacher",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    likes: "13.4k",
    comments: "2.8k",
    shares: "1.5k",
  },
  {
    id: 17,
    name: "Talha Khan",
    profession: "MERN Stack Developer",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    likes: "37.8k",
    comments: "9.2k",
    shares: "5.1k",
  },
  {
    id: 18,
    name: "Sana Riaz",
    profession: "Photographer",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    likes: "29.4k",
    comments: "7.3k",
    shares: "4.0k",
  },
  {
    id: 19,
    name: "Umer Farooq",
    profession: "Tech Blogger",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    likes: "45.6k",
    comments: "11.7k",
    shares: "6.8k",
  },
  {
    id: 20,
    name: "Mehwish Ali",
    profession: "Content Writer",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    likes: "16.7k",
    comments: "3.9k",
    shares: "2.1k",
  },
];

export default users;
